version: '3.8'

services:
  mongo:
    container_name: ${PROJECT_NAME}_mongodb
    build:
      context: .
      dockerfile: Docker/database/Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - ./mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - network

  backend:
    container_name: ${PROJECT_NAME}_backend_app
    build:
      context: .
      dockerfile: Docker/backend/Dockerfile
    volumes:
      - ./dist:/usr/src/app/dist
      - /usr/src/app/node_modules/
    ports:
      - "8001:8001"
    networks:
      - network
    depends_on:
      - mongo
#    command: npm start

networks:
  network:
    driver: bridge




